### ISSUE TITLE
Mock AWS or disable integration-tests when running Travis builds

### ISSUE THREAD

**Issue by DavidBoman** [lambadaframework/lambadaframework#24]
Some tests (e.g.  SimpleStorageServiceWagonIntegrationTest.regionConnections) requires AWS Credentials to run. For obvious reasons these can't be checked in and therefor the build is failing.

This is also a problem in the local build-env as my credentials won't work with your bucket.

**Comment by cagataygurturk** [comment]
You are right! Actually that part of the project is a fork of spring maven wagon project with little modifications. It is unlikely that we change again that part of the project so tests can be excluded.

**Comment by cagataygurturk** [comment]
Fixed by https://github.com/lambadaframework/lambadaframework/commit/8d2e9913554baba11373d942da8fe6bacbe1daab
