### ISSUE TITLE
Add documentation, testcase (and support) for serving HTML

### ISSUE THREAD

**Issue by atramos** [lambadaframework/lambadaframework#43]
It is possible to serve HTML from Lambda via API Gateway:
https://www.google.com/search?q=api+gateway+html+to+browser&ie=utf-8&oe=utf-8

I have checked the boilerplate project's example Controller and I do not see an HTML testcase:
https://github.com/lambadaframework/lambadaframework-boilerplate/blob/master/src/main/java/org/lambadaframework/example/controllers/ExampleController.java

I assume the lack of an example means the HTML serving is not supported. Maybe it is supported and we just need to add it to the example controller.

**Comment by cagataygurturk** [comment]
The project is intended to work for REST API's because it is a JAX-RS implementation. I don't think serving HTML is in scope of this project.
