### ISSUE TITLE
deployment errors (boilerplate project, first time user)

### ISSUE THREAD

**Issue by atramos** [lambadaframework/lambadaframework#47]
After creating a bucket and setting permissions in IAM, execution of mvn deploy fails with this error message:

> 
> [ERROR] Failed to execute goal org.lambadaframework:lambada-maven-plugin:0.0.6:d
> eploy (default) on project boilerplate: Exception at deployment: Cloudformation
> failed. Please check AWS Console for details -> [Help 1]
> 

I checked AWS Console - Lambda, CloudFormation, and Cloud Watch Logs areas - and could not find any indication of what went wrong.

**Comment by cagataygurturk** [comment]
Thanks for reporting. One more user reported a deployment problem, I'll check as soon as possible.

**Comment by atramos** [comment]
Thanks for your attention on this. I have looked into this a lot further and noticed a number of issues. Biggest problem is the boilerplate project still points at lambada 0.0.6, which is very old and has fallen behind in AWS API versions and no longer compatible with current AWS APIs. I noticed another fork is alot newer than the mainline project, and has a rejected Pull Request, so I forked and then pulled changes from that project and started fixing the PR issues. Somebody made some changes to use API Gateway Proxy mode but these appear incomplete as they completely disabled the gateway functionality (I opened another Issue for that). If you have some time, would you please look at [my fork](https://github.com/atramos/lambadaframework) and provide some guidance/suggestions, I believe it is VERY close to working correctly with the boilerplate project on current AWS APIs.
