### ISSUE TITLE
where to configure timeout settings?

### ISSUE THREAD

**Issue by atramos** [lambadaframework/lambadaframework#51]
This is a documentation issue/question.

API Gateway has a default time-out of 29 seconds while Lambda has a default time-out of 30 seconds.

How can I configure both of these through Lambada to a different value?

I'd like to configure through Lambada (configuration as code) instead of directly changing it in AWS Console.

**Comment by cagataygurturk** [comment]
There is a `lambdaMaximumExecutionTime` configuration value you can check out at documentation file.
