### ISSUE TITLE
boilerplate fails to deploy with TooManyRequestsException

### ISSUE THREAD

**Issue by ippeiukai** [lambadaframework/lambadaframework#9]
I've tried https://github.com/lambadaframework/lambadaframework-boilerplate and it failed with TooManyRequestsException. If number of methods is reduced by commenting out some lines in ExampleController, it deploys fine.

You might want to take a look at a similar issue experienced by https://github.com/awslabs/aws-apigateway-importer/issues/149
Their RetryPolicy is found here:
https://github.com/awslabs/aws-apigateway-importer/blob/master/src/com/amazonaws/service/apigateway/importer/config/ApiImporterDefaultModule.java#L87

**Comment by cagataygurturk** [comment]
I also occasionally see this error and actually there is a overhead in develop branch: https://github.com/lambadaframework/lambadaframework/commit/a9c24399ec0ecedcac9a0408d502a070f1e18acb

I'll check the solutions in importer project and try to add to lambada.

**Comment by cagataygurturk** [comment]
I released 0.0.4 that puts more time between requests. Please open this issue again if the problem persists.

Putting sleep is not the best idea, in the next release i'll try to solve it or even we can implement the Cloudformation support announced today.
